"""
Schroedinger's Penalty -- final joint fit and visualization.

Model: the kicker's optimal target density xi(x,z) = u(x,z)^2, where u is the
ground state of

    -grad^2 u + (1/4) V(x,z) u = (1/4) kappa u

on the goal rectangle Omega = [-3.66, 3.66] x [0, 2.44] (metres), with

    V(x,z) = a*U_phys(x,z) - bx*(x-x0)^2 - bz*(z-z0)^2
    U_phys(x,z) = (g/2) * [ sqrt(d^2+x^2+z^2) + z ]

Boundary conditions: u=0 (Dirichlet) at the posts and crossbar; a reflecting
(Neumann) condition du/dz=0 at the ground.

`a` is fixed at 3.31 (independently validated via drag correction and grid
refinement -- an unconstrained joint fit of all five parameters is not
identifiable, since `a` trades off against the height sector along a
shallow ridge). The remaining four parameters (bx, bz, x0, z0) are fit
jointly by maximum likelihood.

Requires: data_xz.npy, an (N,2) array of on-target penalty (x,z) locations
in metres, x = lateral offset from goal centre, z = height above ground.
"""

import numpy as np
from scipy.optimize import minimize
from scipy.linalg import eigh
from scipy.interpolate import RegularGridInterpolator
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------
# 1. Physical constants and grid setup
# ----------------------------------------------------------------------
g = 9.81      # m/s^2
d = 11.0      # penalty-spot-to-goal-line distance, m
a_half = 3.66 # goal half-width, m
b_height = 2.44  # crossbar height, m
A_FIXED = 1.00   # physical-cost weight, fixed (see docstring)

nx, nz = 39, 26
x_full = np.linspace(-a_half, a_half, nx)   # includes Dirichlet boundary at +-a_half
z_full = np.linspace(0, b_height, nz)       # z=0 (Neumann) ... z=b_height (Dirichlet)

# interior unknowns: x indices 1..nx-2 (excluding the two Dirichlet posts);
# z indices 0..nz-2 (z=0 is a genuine unknown under Neumann; z=b_height is Dirichlet)
xi = x_full[1:-1]
zi = z_full[:-1]
dx = x_full[1] - x_full[0]
dz = z_full[1] - z_full[0]
Nx, Nz = len(xi), len(zi)
cellsize = dx * dz

Xg, Zg = np.meshgrid(xi, zi, indexing='ij')
U_phys = (g / 2.0) * (np.sqrt(d**2 + Xg**2 + Zg**2) + Zg)

# 1D second-difference operators
Lx = np.zeros((Nx, Nx))
for i in range(Nx):
    Lx[i, i] = -2.0 / dx**2
    if i > 0:
        Lx[i, i - 1] = 1.0 / dx**2
    if i < Nx - 1:
        Lx[i, i + 1] = 1.0 / dx**2

Lz = np.zeros((Nz, Nz))
for j in range(Nz):
    Lz[j, j] = -2.0 / dz**2
    if j == 0:
        Lz[j, j + 1] = 2.0 / dz**2   # Neumann ghost-point reflection at z=0
    else:
        Lz[j, j - 1] = 1.0 / dz**2
        if j < Nz - 1:
            Lz[j, j + 1] = 1.0 / dz**2

Lap = np.kron(Lx, np.eye(Nz)) + np.kron(np.eye(Nx), Lz)  # 2D discrete Laplacian


def full_grid_density(psi2):
    """Embed the interior-grid density into the full grid, zero at the
    Dirichlet boundaries (posts, crossbar)."""
    full = np.zeros((nx, nz))
    full[1:-1, :-1] = psi2
    return full


def solve_ground_state(V):
    """Solve for the ground state of H = -Lap + (1/4)*diag(V), return the
    normalised density xi = u^2 on the interior grid."""
    H = -Lap + np.diag(0.25 * V.flatten())
    vals, vecs = eigh(H, subset_by_index=[0, 0])
    psi2 = (vecs[:, 0] ** 2).reshape(Nx, Nz)
    psi2 /= psi2.sum() * cellsize
    return psi2


def solve_nll(V, data_xz):
    """Negative log-likelihood of the data under the density generated by V."""
    psi2 = solve_ground_state(V)
    grid = full_grid_density(psi2)
    interp = RegularGridInterpolator((x_full, z_full), grid,
                                      bounds_error=False, fill_value=1e-9)
    dens = np.clip(interp(data_xz), 1e-9, None)
    return -np.sum(np.log(dens))


# ----------------------------------------------------------------------
# 2. The joint fit: (bx, bz, x0, z0), with a fixed at A_FIXED
# ----------------------------------------------------------------------
def nll_joint(params, data_xz):
    bx, bz, x0, z0 = params
    V = A_FIXED * U_phys - bx * (Xg - x0)**2 - bz * (Zg - z0)**2
    return solve_nll(V, data_xz)


def fit_and_report(data_xz, x0_start=(2.56, 64.5, 0.0, 1.05)):
    # optimise
    res = minimize(nll_joint, x0_start, args=(data_xz,), method='Nelder-Mead',
                    options={'xatol': 1e-4, 'fatol': 1e-2, 'maxiter': 600, 'maxfev': 800})
    res = minimize(nll_joint, res.x, args=(data_xz,), method='Nelder-Mead',
                    options={'xatol': 1e-4, 'fatol': 1e-2, 'maxiter': 300, 'maxfev': 400})
    th, f0 = res.x, res.fun

    # full (not per-parameter) finite-difference Hessian, for honest SEs
    h = np.array([0.06, 3.0, 0.02, 0.02])
    H = np.zeros((4, 4))
    for i in range(4):
        ei = np.zeros(4); ei[i] = h[i]
        H[i, i] = (nll_joint(th + ei, data_xz) - 2 * f0 + nll_joint(th - ei, data_xz)) / h[i]**2
    for i in range(4):
        for j in range(i + 1, 4):
            ei = np.zeros(4); ei[i] = h[i]
            ej = np.zeros(4); ej[j] = h[j]
            H[i, j] = H[j, i] = (
                nll_joint(th + ei + ej, data_xz) - nll_joint(th + ei - ej, data_xz)
                - nll_joint(th - ei + ej, data_xz) + nll_joint(th - ei - ej, data_xz)
            ) / (4 * h[i] * h[j])

    eigvals = np.linalg.eigvalsh(H)
    cov = np.linalg.inv(H)
    se = np.sqrt(np.abs(np.diag(cov)))

    bx, bz, x0, z0 = th
    print(f"bx = {bx:.3f} +/- {se[0]:.3f}")
    print(f"bz = {bz:.2f} +/- {se[1]:.2f}")
    print(f"x0 = {x0:.4f} +/- {se[2]:.4f} m")
    print(f"z0 = {z0:.4f} +/- {se[3]:.4f} m")
    print(f"-log L = {f0:.2f}")
    print(f"Hessian eigenvalues: {np.round(eigvals, 3)}  (near-positive => genuine local min)")
    return th, f0, se


# ----------------------------------------------------------------------
# 3. Visualization: three separate single-panel PDFs (density, x-marginal,
#    z-marginal), data vs. fitted model only
# ----------------------------------------------------------------------
def make_figure(data_xz, th,
                 out_density='fig_density.pdf',
                 out_marg_x='fig_marginal_x.pdf',
                 out_marg_z='fig_marginal_z.pdf'):
    bx, bz, x0, z0 = th
    V = A_FIXED * U_phys - bx * (Xg - x0)**2 - bz * (Zg - z0)**2
    psi2 = solve_ground_state(V)
    grid = full_grid_density(psi2)

    marg_x = grid.sum(axis=1) * dz
    marg_x /= marg_x.sum() * dx
    marg_z = grid.sum(axis=0) * dx
    marg_z /= marg_z.sum() * dz

    # (a) fitted density
    fig, ax = plt.subplots(figsize=(6.2, 4.6))
    im = ax.imshow(grid.T, origin='lower', extent=[-a_half, a_half, 0, b_height],
                    aspect='auto', cmap='viridis')
    ax.scatter(data_xz[:, 0], data_xz[:, 1], s=4, c='white', alpha=0.3, edgecolors='none')
    ax.set_xlabel('x, lateral offset (m)'); ax.set_ylabel('z, height (m)')
    ax.set_title(f'Fitted density; n={len(data_xz)} penalties')
    plt.colorbar(im, ax=ax)
    plt.tight_layout()
    plt.savefig(out_density)
    plt.close(fig)
    print(f'saved {out_density}')

    # (b) lateral marginal
    fig, ax = plt.subplots(figsize=(5, 4.6))
    ax.hist(data_xz[:, 0], bins=26, density=True, alpha=0.4, color='gray', label='data')
    ax.plot(x_full, marg_x, color='tab:red', lw=2.4, label='fitted model')
    ax.set_xlabel('x (m)'); ax.set_ylabel('probability density')
    ax.set_title('Lateral marginal'); ax.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(out_marg_x)
    plt.close(fig)
    print(f'saved {out_marg_x}')

    # (c) height marginal
    fig, ax = plt.subplots(figsize=(5, 4.6))
    ax.hist(data_xz[:, 1], bins=20, density=True, alpha=0.4, color='gray', label='data')
    ax.plot(z_full, marg_z, color='tab:red', lw=2.4, label='fitted model')
    ax.set_xlabel('z (m)'); ax.set_ylabel('probability density')
    ax.set_title('Height marginal'); ax.legend(fontsize=9)
    plt.tight_layout()
    plt.savefig(out_marg_z)
    plt.close(fig)
    print(f'saved {out_marg_z}')


# ----------------------------------------------------------------------
# 4. Run
# ----------------------------------------------------------------------
if __name__ == '__main__':
    data_xz = np.load('data_xz.npy')   # (N,2) array: on-target (x,z) in metres
    print(f"n = {len(data_xz)}")

    theta, nll, se = fit_and_report(data_xz)
    make_figure(data_xz, theta)
